### ISSUE TITLE
No unit test for @pattern

### ISSUE THREAD

**Issue by mattbishop** [eddow/ts-json-schema-decorator#1]
I see that you have a `@pattern` decorator but it's not shown in the README or in a unit test.

This is also true for `@format`

**Comment by eddow** [comment]
Well, in case of doubt, the keywords used are the same than for [json-schema](https://json-schema.org/latest/json-schema-validation.html).

`pattern` is a regex that a string should respect
`format` allows keyword-based validation (like 'date' or 'email') - the whole specification is [here](https://json-schema.org/latest/json-schema-validation.html#rfc.section.7)
